name: streak

on:
  schedule:
    - cron: "0 18 * * *"   # once per day (18:00 UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update daily file
        run: echo "$(date -u)" >> daily.txt

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "DarainHyder"
          git config user.email "176991998+DarainHyder@users.noreply.github.com"
          git add daily.txt
          git commit -m "auto streak $(date -u)" || exit 0
          git push https://x-access-token:${GH_TOKEN}@github.com/DarainHyder/Autobot.git HEAD:main